# Factory Demand

## Formulation


Suppose we have 2 factories and 3 destinations

Here, n = 2 and m = 3

We need to determine what quantity of goods each factory will send to each destination

---

### Variables

* A vector `production[2]` storing the production of each factory
* A vector `demand[3]` storing the demand of each destination

So, let us define a matrix `Q[2][3]` such that 
* `Qij` will be the quantity of goods sent from factory i to destination j

---

### Constraints

We need to satisfy the demand
* `Q11` + `Q21` >= `demand[1]`
* `Q12` + `Q22` >= `demand[2]`
* `Q13` + `Q23` >= `demand[3]`

Similarly, we can't exceed the production
* `Q11` + `Q12` + `Q13` <= `production[1]`
* `Q21` + `Q22` + `Q23` <= `production[2]`

Finally, we can't have negative quantities
* `Qij >= 0` for all i, j

---

Genenralizing for m, n

Q to be a matrix of size `n x m`

We have, 
* `Q.T @ np.ones(n) >= demand`
* `Q @ np.ones(m) <= production`
* `Q >= 0`

## Implementation

### Imports

In [ ]:
# imports
import numpy as np
import cvxpy as cp
from matplotlib import pyplot as plt

### Given Data

In [ ]:
n = 3  # Number of factories
production = np.array([40, 50, 45])  
# A vector of size n (Goods Produced by factories)


m = 5  # Number of destinations
demand = np.array([45, 20, 30, 30, 10])
# A vector of size m (Goods required)


# A matrix of size n * m (Cost involved)
C = np.array([
              [8, 6, 10, 9, 8],
              [9, 12, 13, 7, 5],
              [14, 9, 16, 5, 2]
        ])

### Variables


In [ ]:
# We need to calculate
Q = cp.Variable((n, m))

### Objective


In [ ]:
def total_cost(quantities, C):
    return cp.sum(cp.multiply(Q, C))

objective = cp.Minimize(total_cost(Q, C))

### Constraints

In [ ]:
constraints = [
               Q @ np.ones(m) <= production,
               Q.T @ np.ones(n) >= demand,
               Q >= 0
]

### Solving


In [ ]:
prob = cp.Problem(objective, constraints)
result = prob.solve()

### Output

In [ ]:
print("Minimum Cost:", round(result, 3))
print()

with np.printoptions(precision=2, suppress=True):
    print("The Quantities")
    print (Q.value)

Minimum Cost: 1025.0

The Quantities
[[ 0. 15. 25.  0.  0.]
 [45.  0.  5.  0.  0.]
 [ 0.  5.  0. 30. 10.]]
